import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import SlotSelection from './slotSelection/select'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/slotSelection/select">
          <button className='font-semibold p-4 text-xl bg-purple-600 shadow-lg text-white rounded-lg'>
            Book Appointment
          </button>
        </Link>
      </main>
    </div>
  )
}

export default Home
